# Generated by Django 3.2.5 on 2021-07-29 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210729_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=1012),
        ),
        migrations.CreateModel(
            name='b_issue_mt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2021, 7, 29))),
                ('status', models.IntegerField(default=1)),
                ('bk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.student')),
            ],
        ),
    ]
