# Generated by Django 3.2.5 on 2021-07-29 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20210729_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_issue_mt',
            name='total',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='b_issue_mt',
            name='date',
            field=models.DateField(default=datetime.date(2021, 7, 30)),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=838),
        ),
    ]
