# Generated by Django 3.2.5 on 2021-07-29 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20210730_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_issued_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('s_name', models.CharField(max_length=50)),
                ('totalm', models.BigIntegerField()),
                ('date', models.DateField(default=datetime.date(2021, 7, 30))),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=392),
        ),
    ]
