# Generated by Django 3.2.5 on 2021-07-30 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20210730_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bk_is_dt',
            name='b_is_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book_issued_m'),
        ),
        migrations.AlterField(
            model_name='bk_is_dt',
            name='b_m_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=152),
        ),
    ]
