# Generated by Django 3.2.5 on 2021-07-31 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b_issue_mt',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
        migrations.AlterField(
            model_name='bk_is_dt',
            name='re_date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
        migrations.AlterField(
            model_name='bk_is_t',
            name='b_is_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bk_is_t',
            name='b_m_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='bk_is_t',
            name='re_date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
        migrations.AlterField(
            model_name='book_issued_m',
            name='date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=262),
        ),
        migrations.CreateModel(
            name='overall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('total', models.BigIntegerField(default=1)),
                ('date', models.DateField(default=datetime.date(2021, 8, 1))),
                ('status', models.IntegerField(default=1)),
                ('bk_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books')),
                ('s_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.student')),
            ],
        ),
    ]
