# Generated by Django 3.2.5 on 2021-08-01 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bk_is_dt',
            name='b_is_id',
        ),
        migrations.RemoveField(
            model_name='bk_is_dt',
            name='b_m_id',
        ),
        migrations.AddField(
            model_name='bk_is_t',
            name='iss_date',
            field=models.DateField(default=datetime.date(2021, 8, 1)),
        ),
        migrations.AlterField(
            model_name='bk_is_t',
            name='re_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=984),
        ),
        migrations.DeleteModel(
            name='b_issue_mt',
        ),
        migrations.DeleteModel(
            name='bk_is_dt',
        ),
    ]
